# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_days.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(231, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.box_monday = QtWidgets.QCheckBox(Dialog)
        self.box_monday.setObjectName("box_monday")
        self.btn_group_days = QtWidgets.QButtonGroup(Dialog)
        self.btn_group_days.setObjectName("btn_group_days")
        self.btn_group_days.setExclusive(False)
        self.btn_group_days.addButton(self.box_monday)
        self.verticalLayout_2.addWidget(self.box_monday)
        self.box_tuesday = QtWidgets.QCheckBox(Dialog)
        self.box_tuesday.setObjectName("box_tuesday")
        self.btn_group_days.addButton(self.box_tuesday)
        self.verticalLayout_2.addWidget(self.box_tuesday)
        self.box_wendesday = QtWidgets.QCheckBox(Dialog)
        self.box_wendesday.setObjectName("box_wendesday")
        self.btn_group_days.addButton(self.box_wendesday)
        self.verticalLayout_2.addWidget(self.box_wendesday)
        self.box_thursday = QtWidgets.QCheckBox(Dialog)
        self.box_thursday.setObjectName("box_thursday")
        self.btn_group_days.addButton(self.box_thursday)
        self.verticalLayout_2.addWidget(self.box_thursday)
        self.box_friday = QtWidgets.QCheckBox(Dialog)
        self.box_friday.setObjectName("box_friday")
        self.btn_group_days.addButton(self.box_friday)
        self.verticalLayout_2.addWidget(self.box_friday)
        self.box_saturday = QtWidgets.QCheckBox(Dialog)
        self.box_saturday.setObjectName("box_saturday")
        self.btn_group_days.addButton(self.box_saturday)
        self.verticalLayout_2.addWidget(self.box_saturday)
        self.box_sunday = QtWidgets.QCheckBox(Dialog)
        self.box_sunday.setObjectName("box_sunday")
        self.btn_group_days.addButton(self.box_sunday)
        self.verticalLayout_2.addWidget(self.box_sunday)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Выберите дни"))
        self.box_monday.setText(_translate("Dialog", "Понедельник"))
        self.box_tuesday.setText(_translate("Dialog", "Вторник"))
        self.box_wendesday.setText(_translate("Dialog", "Среда"))
        self.box_thursday.setText(_translate("Dialog", "Четверг"))
        self.box_friday.setText(_translate("Dialog", "Пятница"))
        self.box_saturday.setText(_translate("Dialog", "Суббота"))
        self.box_sunday.setText(_translate("Dialog", "Воскресенье"))
